### ISSUE TITLE
Uncaught TypeError: Cannot read property 'localStorage' of undefined

### ISSUE THREAD

**Issue by wayneashleyberry** [jeromegn/Backbone.localStorage#130]
Trying out localStorage for the first time. I get this error regardless of trying requirejs or straight up script tags.

```
Uncaught TypeError: Cannot read property 'localStorage' of undefined
[backbone.localStorage.js:233]
```

Here's my javascript.

```javascript
requirejs.config({
  baseUrl: '/js',
  paths: {
    jquery       : 'lib/jquery',
    underscore   : 'lib/lodash',
    backbone     : 'lib/backbone',
    localstorage : 'lib/backbone.localStorage',
    moment       : 'lib/moment'
  }
});

requirejs(['backbone', 'moment', 'localstorage'],
function (Backbone, moment, localstorage) {
  var Articles = Backbone.Collection.extend({
    localStorage: new Backbone.LocalStorage("articles")
  });

  var articles = new Articles();

  articles.add([
    {createdAt: moment(), updatedAt: moment()}
  ]);

  articles.sync();
});
```

**Comment by Loxyboi** [comment]
I get this error every time as well when calling sync() on a collection. Has a solution been found?

**Comment by jeromegn** [comment]
Let me know if this still happens with `1.1.16`.

**Comment by nobleach** [comment]
I npm installed it and required it in a collection. When I try to run my unit tests, I get:

```Running "mochaTest:test" (mochaTest) task
>> Mocha exploded!
>> ReferenceError: localStorage is not defined
>>     at extend.localStorage (/Users/jimwharton/Sites/overstock.com/assets/node_modules/backbone.localstorage/backbone.localStorage.js:137:12)
>>     at new Backbone.LocalStorage.window.Store (/Users/jimwharton/Sites/overstock.com/assets/node_modules/backbone.localstorage/backbone.localStorage.js:72:20)
>>     at Object.<anonymous> (/Users/jimwharton/Sites/overstock.com/assets/src/search-suggestion/collections/recent-search-collection.js:6:19)
>>     at Module._compile (module.js:456:26)
>>     at Object.Module._extensions..js (module.js:474:10)
>>     at Module.load (module.js:356:32)
>>     at Function.Module._load (module.js:312:12)
>>     at Module.require (module.js:364:17)
>>     at require (module.js:380:17)
>>     at Object.<anonymous> (/Users/jimwharton/Sites/overstock.com/assets/test/spec/search-suggestion/collections/recent-search-collection-test.js:3:30)```

**Comment by nobleach** [comment]
Is the fix to also include it in the model as well?

**Comment by ashishsajwan** [comment]
now it shows `Cannot read property 'collection' of undefined` @jeromegn
